gaussian_dim: 4
time_duration: [0.0, 10.0]
num_pts: 300_0000
num_pts_ratio: 1.0
rot_4d: False
force_sh_3d: True
batch_size: 4
exhaust_test: False
# start_checkpoint: "output/$dataset/chkpnt6000.pth"


ModelParams:
  sh_degree: 3
  # source_path: ".../$dataset"
  # model_path: "output/$dataset"
  images: "images"
  resolution: 1 # use 2 for the original resolution dataset!
  white_background: False
  data_device: "cuda"
  eval: True
  extension: ".png"
  num_extra_pts: 0
  loaded_pth: ""
  frame_ratio: 1
  dataloader: True

PipelineParams:
  convert_SHs_python: False
  compute_cov3D_python: False
  debug: False
  env_map_res: 0
  env_optimize_until: 5000000000
  env_optimize_from: 0
  eval_shfs_4d: True

OptimizationParams:
  iterations: 6_000
  position_lr_init: 0.00016
  position_t_lr_init: -1.0
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30_000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.005
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  thresh_opa_prune: 0.005
  densification_interval: 100
  opacity_reset_interval: 30000
  densify_from_iter: 500
  densify_until_iter: 15_000
  densify_grad_threshold: 0.0002
  densify_grad_t_threshold: 0.0002 / 40
  densify_until_num_points: -1
  final_prune_from_iter: -1
  sh_increase_interval: 1000
  lambda_opa_mask: 0.0
  lambda_rigid: 0.0
  lambda_motion_gate: 0.05
  static_conversion_threshold: 2.0
  lambda_sparsity: 0.05
  gate_activation_iter: 10000
  gate_warmup_until_iter: 20000